month: 202601
date: null
pool: hs300
output_dir: null
save_detail: false
n_jobs: 4

ddb:
  server: localhost
  port: 8902
  userName: admin
  userKey: "123456"
  timeout: 3600

mysql:
  host: 127.0.0.1
  port: 3306
  user: quantStrat
  password: eqalgo_2024
  database: strategy

ticker_source: return_table
indus_table_suffix: ""
avg_price: 10
price_name: highprice
trading_hours: null
min_cross_section_size: 30

factor_table_groups:
  - long_term_factor_table_15s

return_table_name: Returns_long_short_hs300

return_cols:
  - long_ret_10min
  - long_ret_20min
  - long_ret_30min

factor_groups:
  - long_term_base_factor_15s
