name: train_lgbm_300s
manual_seed: 2023
n_jobs: 8

# factor dataset
dataset:
  backtest_month: [202304, 202305, 202306]
  io_backend: sql # disk
  pool_name: ['hs300', 'zz500']
  indus_class: wind1
  avg_price: 10
  is_highprice: True
  ret_name: 300s

  std_type: default # trainingset std
  alpha: 0.001
  class_num: 2
  balance: reverse

train:
  num_epoch: 200
test:
  bound_mode: by_ticker # indus
  threshold_pct: 5

network:
  name: lgbm
  n_cpus: 10


